### ISSUE TITLE
O arquivo abre mas não é legível

### ISSUE THREAD

**Issue by davirs** [Rechdan/WYD-strdef-editor#1]
Muito boa a iniciativa e o formato dos programas!!! O itemlist está perfeito!

Consegue me ajudar aqui? Quando eu abro o arquivo strdef.bin ele abre assim:

![image](https://user-images.githubusercontent.com/4355062/80925196-3d206280-8d64-11ea-86f3-2af5fc0d30c4.png)

outra coisa, qual é o endereço da comunidade wyd private?
Obrigado! um grande abraço

**Comment by Rechdan** [comment]
Fala @davirs!

Olha, pelo que to vendo seu arquivo já foi decodificado, no caso esse editor ele já abre e decodifica sozinho, então só rodar um `xor 0x5A` e salvar que, quando ele abrir, vai aparecer os textos normalmente! 😀

E aqui está o convite pro grupo: [WYD Private](https://discord.gg/YQQNtmN)

**Comment by davirs** [comment]
Valeu irmão, parabéns pelo trabalho

Não entendo nada de C, mas vou dar uma fuçada aqui
Abraço
